nelmio_api_doc:
    models:
        # use_jms: true
    documentation:
        info:
            title: GitHub repository comparison tool
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$)
